// Auto-generated by ResourceTypeGenerator
public static partial class ResourceType
{
    public const string Datas = "Datas";
    public const string FontsMaterials = "Fonts & Materials";
    public const string Prefabs = "Prefabs";
    public const string SpriteAssets = "Sprite Assets";
    public const string StyleSheets = "Style Sheets";
    public const string Thumbnails = "Thumbnails";
public const string Scene = "Scene";
public const string UI = "UI";
public const string Audios = "Audios";
public const string Thumbnail = "Thumbnail";
}
