using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Ironcow.Synapse;
using UnityEngine.UI;
using Ironcow.Synapse.UI;
using TMPro;

public class UIMain : UIBase
{
    #region AutoGenerated
    [SerializeField] private Image image;
    [SerializeField] private TMP_Text textTMP;
    #endregion
    public override void Opened(object[] param)
    {
        base.Opened(param);

    }

    public override void HideDirect()
    {
        UIManager.Hide<UIMain>();
    }
}
