// <auto-generated>
// This file is generated by ScriptTemplateMenuBuilder.
// Do not modify manually.
// </auto-generated>

using UnityEngine;
using UnityEditor;
using Ironcow.Synapse.Common;

public static class ScriptTemplateMenu_SynapseBehaviour
{
	[MenuItem("GameObject/Create and Add Script/Custom/SynapseBehaviour", false, -10)]
	public static void Create_SynapseBehaviour()
	{
		ScriptTemplateExecutor.GenerateAndAttachScript(typeof(SynapseBehaviour));
	}
}
