// <auto-generated>
// This file is generated by ScriptTemplateMenuBuilder.
// Do not modify manually.
// </auto-generated>

using UnityEngine;
using UnityEditor;
using Ironcow.Synapse.Common;

public static class ScriptTemplateMenu_CanvasBase
{
	[MenuItem("GameObject/Create and Add Script/Custom/CanvasBase", false, -10)]
	public static void Create_CanvasBase()
	{
		ScriptTemplateExecutor.GenerateAndAttachScript(typeof(Ironcow.Synapse.UI.CanvasBase));
	}
}
