// <auto-generated>
// This file is generated by ScriptTemplateMenuBuilder.
// Do not modify manually.
// </auto-generated>

using UnityEngine;
using UnityEditor;
using Ironcow.Synapse.Common;

public static class ScriptTemplateMenu_UIBase
{
	[MenuItem("GameObject/Create and Add Script/Custom/UIBase", false, -10)]
	public static void Create_UIBase()
	{
		ScriptTemplateExecutor.GenerateAndAttachScript(typeof(Ironcow.Synapse.UI.UIBase));
	}
}
